version: '3'


networks:
  p2p-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  build-container:
    build:
      context: .
      dockerfile: ./docker/build/Dockerfile
  central-container:
    build:
      context: .
      dockerfile: ./docker/central/Dockerfile
    volumes: ['./evaluation:/home/threePP']
    environment:
      - nodes=8
    networks:
      p2p-network:
        ipv4_address: 172.28.1.1
  three-pp-container:
    build:
      context: .
      dockerfile: ./docker/threePP/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - type=0
      - threads=1
      - senders=1
      - msgsize=512
      - delay=100
    networks:
      p2p-network: