version: '3'


networks:
  p2p-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  build-container:
    build:
      context: .
      dockerfile: ./docker/build/Dockerfile
  central-container:
    build:
      context: .
      dockerfile: ./docker/central/Dockerfile
    networks:
      p2p-network:
        ipv4_address: 172.28.1.1
  three-pp-container:
    build:
      context: .
      dockerfile: ./docker/threePP/Dockerfile
    networks:
      p2p-network: